### ISSUE TITLE
Allocate direct buffers

### ISSUE THREAD

**Issue by Zakru** [jroyalty/jglm#18]
Currently the value buffers used by the various vectors and matrices are not directly allocated, which results in them being unusable with libraries such as LWJGL by themselves. It would remove a lot of hassle if they were directly allocated.

**Comment by jroyalty** [comment]
You can actually change this behavior by implementing a new `BufferAllocator` and setting it by via config in https://github.com/jroyalty/jglm/blob/master/src/main/java/com/hackoeur/jglm/buffer/BufferAllocatorFactory.java

**Comment by Zakru** [comment]
Oh, I did not look around the code that much and it wasn't immediately clear. Will look into it more.
