### ISSUE TITLE
Maven central release

### ISSUE THREAD

**Issue by Zubnix** [jroyalty/jglm#6]
I like this library. It should be in the central maven repository, so I don't have to build it separately.

**Comment by jroyalty** [comment]
Okay, I'll work on getting it published there.  Shouldn't be hard since it already builds via Maven.

**Comment by jroyalty** [comment]
Submitted request for ability to publish to central.  Should hear back in the next couple of days.

**Comment by jitpack** [comment]
In the meantime the library is easily available on https://jitpack.io/#jroyalty/jglm/1.0.0-SNAPSHOT : )

**Comment by jroyalty** [comment]
@jitpack That's a pretty cool service!

**Comment by jitpack** [comment]
@jroyalty Glad you like it!:) It works well with GitHub releases https://github.com/jroyalty/jglm/releases

**Comment by jroyalty** [comment]
Okay, got the Maven central creds.  I'll publish when I get a chance.

**Comment by Zubnix** [comment]
*waiting intensifies*

**Comment by jroyalty** [comment]
All done.  JGLM is now available in Maven central using:

```
<dependency>
    <groupId>com.hackoeur</groupId>
    <artifactId>jglm</artifactId>
    <version>1.0.0</version>
</dependency>
```
